### ISSUE TITLE
Code does not compile - errors

### ISSUE THREAD

**Issue by AlekseySkuratov** [craigg96/vesc_can_bus_arduino#2]
Hello!
I tried your library and example - unfortunately nothing works.

Errors:
__/Users/aleksey/Documents/Arduino/libraries/vesc_can_bus/vesc_can_bus.cpp:6:6: error: 'CAN' has not been declared
 void CAN::initialize() {
      ^~~
/Users/aleksey/Documents/Arduino/libraries/vesc_can_bus/vesc_can_bus.cpp:12:6: error: 'CAN' has not been declared
 void CAN::spin() {
      ^~~
/Users/aleksey/Documents/Arduino/libraries/vesc_can_bus/vesc_can_bus.cpp: In function 'void spin()':
/Users/aleksey/Documents/Arduino/libraries/vesc_can_bus/vesc_can_bus.cpp:13:3: error: 'get_frame' was not declared in this scope
   get_frame();_

... and etc.

Can you tell what could be the problem?

Thank you!
Best regards, Aleksey

![Снимок экрана 2022-08-17 в 08 58 31](https://user-images.githubusercontent.com/53623769/185054967-93aeb82f-a5d5-46f6-a509-afc939eeab76.png)

**Comment by adrientsmith** [comment]
Add the line

```#include vesc_can_bus_arduino.h```

to vesc_can_bus_arduino.cpp.

**Comment by IHateNameStealers** [comment]
Did you guys manage to compile this?
I keep getting an "undefined reference to `setup'" error when compiling it!
Any help appreciated!

**Comment by benebeneIBK** [comment]
Hi,

I am also trying to use the library and updated the header file name. Unfortunately, I always receive a Waring, and it seems like that no instance of the class CAN has been declared. Can you help me on this?  Thanks!
![grafik](https://user-images.githubusercontent.com/122271188/211290201-066bdf4d-142d-4c49-9c30-6c9e5aaf5100.png)

**Comment by IHateNameStealers** [comment]
Did you put the "vesc_can_bus_arduino.cpp" and the "vesc_can_bus.h" in the same directory as your project file ?

Also for me I needed to change the 

#include <vesc_can_bus_arduino.h> 
to 
#include "vesc_can_bus_arduino.h"

**Also** You will need to change **void setup_()** to **void setup()**
(see: https://github.com/craigg96/vesc_can_bus_arduino/issues/3 )

After this all worked fine for me.

**Comment by benebeneIBK** [comment]
HI IHateNameStealers,

thank you very much for your replay and effort!
I tried your suggestions, but now I am receiving a different Error. It seems like there is something missing in the mcp_can.cpp library. If I check the mcp_can.cpp for "MCP_CLOCK_SELECT" I can find it once. However, I cannot image that the library itself has issues, because it seems to be widely used. 
All the files in the same folder: (I suggest with "vesc_can_bus.h" you mean "vesc_can_bus_arduino.h")

Did you have to change anything else?
I appreciate your help!

![grafik](https://user-images.githubusercontent.com/122271188/213860509-14af3ae5-8bdb-4c68-a012-86f20a698285.png)
![grafik](https://user-images.githubusercontent.com/122271188/213861077-25fd49f0-839d-43f5-99cc-83f9ec5b5dd0.png)
![grafik](https://user-images.githubusercontent.com/122271188/213861120-5e22fe9c-41ce-426a-8bb2-71dfc23d0320.png)

**Comment by kbgajjar27** [comment]
hi can you please tell me which pin or gpio pin, you attach the mcp with arduino ?

and how can i change the pin ? because i am using your lib on esp32 dev module and on that the gpio pin 4 (as rx of can) and gpio pin 16 (as tx of can) are for can communication

**Comment by IHateNameStealers** [comment]
I'm using pin 10, and you can change it within the "vesc_can_bus_arduino.cpp"
See: MCP_CAN CAN0(10);                               // Set CS to pin 10

**Comment by craigg96** [comment]
Hi,
I have resolved the issue
- Forgot to declare the header file in the .cpp.
- .ino file had bad decleration
- Setup function had a typo.

Sorry i uploaded this library in a rush 👍
